import "./globals.css";
import Navbar from "@/components/navbar";
import { Outfit, DM_Sans } from "next/font/google";

export const outfit = Outfit({ subsets: ["latin"] });
export const dmsans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outfit.className}`}>
      <body
        className={`w-screen relative bg-black text-white overflow-x-hidden `}
      >
        {children}
      </body>
    </html>
  );
}
